server:
  port: 8080

spring:
  application:
    name: ml-algorithm

logging:
  level:
    root: INFO
    com.example.mlalgorithm: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 